### ISSUE TITLE
problems with downloading / installing mysql on centos 6

### ISSUE THREAD

**Issue by dannymell** [Karmel0x/lastchaos-server-install-stuff#5]
please help ive been trying to get mysql on centos 6 for weeks also tried all the steps you showed but none work

**Comment by Karmel0x** [comment]
Would be great if you can tell where exactly you have problem or show some logs with errors.

I've checked links and replaced one dead. Maybe try now.

**Comment by dannymell** [comment]
> Would be great if you can tell where exactly you have problem or show some logs with errors.
> 
> I've checked links and replaced one dead. Maybe try now.

im trying the lc sever build on centos 6 
so idk if im messing up or its not for centos 6

**Comment by Karmel0x** [comment]
Oh, I missed the "mysql" part.

You can find link here: https://mariadb.org/download/?t=mariadb&p=mariadb&r=10.5.17&os=source&m=archive
If you have problems with installing, try putting [my.cnf](https://github.com/Karmel0x/lastchaos-server-install-stuff/blob/master/install_linux_mysql_my.cnf) to `/etc/my.cnf` then use `/etc/init.d/mysql start` to start server.
